### ISSUE TITLE
Pimp Facebook Share Thumbnail

### ISSUE THREAD

**Issue by n1cus** [rubyargentina/rubyconfar-2014#16]
Make Facebook show the newly added "thumbnail.jpg" as a thumbnail when sharing the url.

Debugging tool: https://developers.facebook.com/tools/debug/og/object/

![facebook](https://cloud.githubusercontent.com/assets/796924/3914357/04b64b74-2345-11e4-8b10-a693995243fe.png)
![thumbnail](https://cloud.githubusercontent.com/assets/796924/3914358/066be9b0-2345-11e4-9e73-2554a9441cd9.jpg)

**Comment by lucasefe** [comment]
Done.

**Comment by n1cus** [comment]
Team team team.
