### ISSUE TITLE
Smart Navigation

### ISSUE THREAD

**Issue by n1cus** [rubyargentina/rubyconfar-2014#2]
Make navigation items get the 'active' class when scrolling through corresponding section.

Also, when clicking on the circles, the 'active' class must be applied once the scrolling has reached its destination.

Example here: http://www.freshbooks.com/tour.php

**Comment by n1cus** [comment]
✓ Done.
Took care of it with a nice jquery plugin.

**Comment by ceneon** [comment]
✓ deployed
