### ISSUE TITLE
Add Ruby Fun Day to the site

### ISSUE THREAD

**Issue by ceneon** [rubyargentina/rubyconfar-2014#24]
El Ruby Fun Day es un día completo de talleres de lo más variados. Habrá actividades para Rubyistas principiantes, y también para experimentados.

Estos talleres se dan en un entorno de aulas, permitiendo mayor participación de los asistentes.

Para aprovechar los talleres al máximo, es necesario disponer de una laptop.

El Ruby Fun Day 2014 será el 23 de Octubre, un día antes de la conferencia, en la Universidad de Palermo: Mario Bravo 1050. 

La inscripción para el Ruby Fun Day es gratuita y comenzará pronto, con prioridad para los inscriptos a RubyConf Argentina.

---

Ruby Fun Day is a full day of workshops. There will be activities for beginner Rubyists, and also for the experienced ones. 

These workshops will take place in classrooms, so there's more interaction from attendees. 

A laptop is suggested to participate in the workshops. 

The 2014 edition of Ruby Fun Day will be on October 23rd, one day before the conference, at Universidad de Palermo: Mario Bravo 1050. 

Registration for Ruby Fun Day is free and will open soon, with priority for the attendees of RubyConf Argentina

**Comment by n1cus** [comment]
![rfd](https://cloud.githubusercontent.com/assets/796924/4189429/5528a8fe-377c-11e4-94aa-33b5c58c3d93.png)

**Comment by ceneon** [comment]
:thumbsup: :surfer:

**Comment by n1cus** [comment]
Lo pongo a continuación de "CONVOCATORIA A CHARLAS" ?

**Comment by ceneon** [comment]
:ok_hand:

**Comment by n1cus** [comment]
**✓ Ready for deploy.**

**Comment by n1cus** [comment]
_Note:_ UP location is currently opening in Mapa de Buenos Aires in a new tab, will change to Google Maps and some fancy lightbox.

**Comment by ceneon** [comment]
Por mí está bien así lo del mapa. No vale la pena nada más.

**Comment by ceneon** [comment]
![53311945](https://cloud.githubusercontent.com/assets/530965/4196276/af7d37e4-37d0-11e4-8362-e6ea254b7803.jpg)
