### ISSUE TITLE
Details Layout

### ISSUE THREAD

**Issue by n1cus** [rubyargentina/rubyconfar-2014#25]
Create a layout (probably 2 columns) that can be used for Sponsors, detalle de las charlas, etc.

**Comment by ceneon** [comment]
![](http://cdn5.movieclips.com/fox/o/office-space-1999/0365066_13327_MC_UTx360.jpg)

**Comment by n1cus** [comment]
[![I was gonna, but then I got high.](http://img.youtube.com/vi/WeYsTmIzjkw/1.jpg)](http://www.youtube.com/watch?v=WeYsTmIzjkw)

**Comment by ceneon** [comment]
jajaja

**Comment by n1cus** [comment]
Basic **Details Layout** in place. 
Style fine-tuning needs to take place when actual content is applied.

details-layout.html.haml
