### ISSUE TITLE
Edit Esteban Pastorino & Ignacio Gutierrez pics

### ISSUE THREAD

**Issue by ceneon** [rubyargentina/rubyconfar-2014#26]
https://github.com/rubyargentina/rubyconfar-2014/blob/master/resources/speakers/Esteban%20Pastorino.jpg
https://github.com/rubyargentina/rubyconfar-2014/blob/master/resources/speakers/Ignacio%20Gutierrez.jpeg

@n1cus

**Comment by n1cus** [comment]
✓ Done.
Nico, fijate que sendos ñatos tienen el mismo nombre de charla, es correcto o es un olvido de copy-paste?

**Comment by ceneon** [comment]
@n1cus Es correcto! Dan el taller entre los dos y se decidió subirlos por separado

**Comment by ceneon** [comment]
@n1cus creo que acá me perdí de algo... con tener las imágenes cuadradas, el CSS ya les da estilo suficiente?

**Comment by n1cus** [comment]
Si, pero yo les aplico unos efectos en Photoshop, así que siempre tienen que pasar por mí.

**Comment by ceneon** [comment]
ah está bien... es que mi ojo no-diseñador las veía igual estas dos.

_Nicolás Cerrini_
http://www.neurosys.com.ar  http://www.flickr.com/photos/ceneon
http://www.facebook.com/nicolas.cerrini  http://twitter.com/ceneon
