### ISSUE TITLE
Google Maps inside Magnific Popup

### ISSUE THREAD

**Issue by n1cus** [rubyargentina/rubyconfar-2014#28]
Deosn't work, console says:

``` javascript
Refused to display 'https://www.google.com.ar/maps/place/Mario+Bravo+1050,+Buenos+Aires,+Ciudad…72,17z/data=!3m1!4b1!4m2!3m1!1s0x95bcca87df85cc47:0x5386f54481530905?hl=en' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

Tried declaring my (personal) Google API as per:
https://developers.google.com/maps/documentation/javascript/tutorial#api_key
but still fails.

![grumpy cat](https://cloud.githubusercontent.com/assets/796924/4220542/be97b588-3901-11e4-8229-331c030d1e26.gif)

**Comment by ceneon** [comment]
https://github.com/rubyargentina/rubyconfar-2014/commit/5e7217220cf560c0f16cff3628eef852ff0d8c38 Some google maps mumbo-jumbo

![20080517165120 mumbo_jumbo](https://cloud.githubusercontent.com/assets/530965/4226278/1b55e144-3936-11e4-8bdc-795fb92ff493.jpg)

**Comment by n1cus** [comment]
![18ef0e8f-284c-443d-a6e4-5b20b5d438d4 fibertel com ar](https://cloud.githubusercontent.com/assets/796924/4226343/911b2538-3936-11e4-8aee-ba6bce45a286.gif)

**Comment by ceneon** [comment]
jajajja
