### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by n1cus** [rubyargentina/rubyconfar-2014#29]
Nice design for venue by Laura.

![rc-konex](https://cloud.githubusercontent.com/assets/796924/4305320/428a1d42-3e78-11e4-97d7-08b29e58305f.jpg)

**Comment by ceneon** [comment]
:shipit: NOW

**Comment by inkel** [comment]
¡TREMENDO!

**Comment by n1cus** [comment]
Pueden mandar su ♥ a laura@SzStudios.net
Esta semana lo maqueto.

**Comment by n1cus** [comment]
Done.
Popup map doesn't seem to be working.

**Comment by ceneon** [comment]
The popup was working before :/

**Comment by n1cus** [comment]
I broke the internet.

On September 18, 2014 at 1:36:38 PM, Nicolás Cerrini (notifications@github.com) wrote:

The popup was working before:/

**Comment by ceneon** [comment]
![it_crowd___the_internet_by_surlana](https://cloud.githubusercontent.com/assets/530965/4323645/51887994-3f52-11e4-9854-7587577f2535.jpg)
