### ISSUE TITLE
Deviget Bronze 

### ISSUE THREAD

**Issue by lucasefe** [rubyargentina/rubyconfar-2014#30]
Pretty please?

**Comment by n1cus** [comment]
Will think about it.

![](http://img3.wikia.nocookie.net/__cb20090317220205/killbill/images/f/fa/Budd.jpg)

**Comment by n1cus** [comment]
✓ Done.

![](http://moviesmedia.ign.com/movies/image/michaelmadsen_killbillvol2_inline_1081963227.jpg)
