### ISSUE TITLE
Add trinity to the mix

### ISSUE THREAD

**Issue by lucasefe** [rubyargentina/rubyconfar-2014#8]

**Comment by n1cus** [comment]
![matrix___trinity___entance_by_iacovos10](https://cloud.githubusercontent.com/assets/796924/3782298/12802756-19a0-11e4-876a-654f636122f0.jpg)

**Comment by inkel** [comment]
![image](https://cloud.githubusercontent.com/assets/108421/3782453/4ae17706-19a2-11e4-997a-6821af41d21a.png)

![image](https://cloud.githubusercontent.com/assets/108421/3782466/731ead2e-19a2-11e4-81e8-de81c57173b9.png)

**Comment by n1cus** [comment]
Done.

**Comment by inkel** [comment]
Excelente!!!

**Comment by lucasefe** [comment]
Sos mi ídolo.

_Lucas_
@lucasefe
http://www.lucasefe.com.ar/
"When life is hard, you have to change. " S. Hoon
